version: '3'
services:
  activity_service:
    build: ./
    container_name: activity_service
    ports:
      - '${BACKEND_PORT}:3000'
    depends_on:
      - activities_db
    networks:
      - collabvr_network
    env_file:
      - .env

  activities_db:
    image: postgres:13
    container_name: activities_db
    env_file:
      - .env
    ports:
      - '${DB_PORT}:5432'
    networks:
      - collabvr_network

networks:
  collabvr_network:
    driver: bridge
